In [ ]:
#Create a list of numbers from 1 to 20 using list comprehension.
l =[]
for i in range(1, 21):
  l.append(i)

print(l)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [ ]:
#Generate a list of squares for numbers from 1 to 10.
l_2= []
i=0
for i in range(1,11):
  l_2.append(i**2)
print(l_2)


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
#Convert all words in a list to lowercase using list comprehension
k =["pavAn", "BHaskar"]
p= "LaKshman"
print(p.lower())
emp = []
i=0
for i in k:
  emp.append(i.lower())

print(emp)
print(k)



lakshman
['pavan', 'bhaskar']
['pavAn', 'BHaskar']


In [ ]:
#Create a list of all even numbers from 1 to 50.
l=[]
for i in range(1,51):
  if i%2==0:
    l.append(i)
print(l)


[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]


In [ ]:

#Extract all vowels from a string into a list.
st = "Brianna Hildebrand"
v =[]
for char in st:
  if char in "aeiouAEIOU":
    v.append(char)
print(v)


['i', 'a', 'a', 'i', 'e', 'a']


In [ ]:
#Create a list of tuples, where each tuple contains a number and its cube for numbers from 1 to 10.
p =[]
for i in range(1,11):
  p.append((i, i**3))
print(p)

[(1, 1), (2, 8), (3, 27), (4, 64), (5, 125), (6, 216), (7, 343), (8, 512), (9, 729), (10, 1000)]


In [ ]:
#Flatten a 2D list into a single list.

import itertools
two_d_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9],[7,9,0]]
flattened_list = list(itertools.chain(*two_d_list))
print(flattened_list)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 7, 9, 0]


In [ ]:
#Use list comprehension to filter out non-prime numbers from a given list of integers.
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False

is_prime(45)

False

In [ ]:
#Create a list of palindromic words from a list of strings.
word = "madam"
if word == word[::-1]:  # word[::-1] reverses the string
    print("It's a palindrome!")
else:
    print("It's not a palindrome.")


It's a palindrome!


In [ ]:
#Create a set of unique characters from the string "hello world".
string = "hello world"
unique_chars = set(string)
print(unique_chars)

{' ', 'r', 'w', 'e', 'd', 'l', 'o', 'h'}


In [ ]:
#Generate a set of squares of numbers from 1 to 10.

# Generate a set of squares of numbers from 1 to 10
squares = {x ** 2 for x in range(1, 11)}

# Print the set of squares
print(squares)


{64, 1, 4, 36, 100, 9, 16, 49, 81, 25}


In [ ]:
#Find the unique lengths of words in a given sentence.
k = "pavan kumar"
s = k.split()
print(type(s))
print(len(k))
print(len(s))

<class 'list'>
11
2


In [ ]:
#Generate a set of numbers from 1 to 50 that are divisible by both 2 and 3.
n = 50
set_n = set()
for n in range(1,51):
  if n%2==0 and n%3==0:
    set_n.add(n)
print(set_n)

{36, 6, 42, 12, 48, 18, 24, 30}


In [ ]:
#Generate a set of common factors of two given numbers using a set comprehension.
def common_factors(a, b):
    # Use set comprehension to find common factors of a and b
    return {x for x in range(1, min(a, b) + 1) if a % x == 0 and b % x == 0}

# Example input
a = 36
b = 60

# Get common factors of a and b
factors = common_factors(a, b)

# Print the result
print(factors)


{1, 2, 3, 4, 6, 12}


In [ ]:
#Create a dictionary where keys are numbers from 1 to 5, and values are their squares.
squares_dict = {1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
print(squares_dict)


{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [ ]:
#Convert a list of words into a dictionary with words as keys and their lengths as values.
words = ['apple', 'banana', 'cherry', 'date']
word_lengths = {word: len(word) for word in words}

print(word_lengths)


{'apple': 5, 'banana': 6, 'cherry': 6, 'date': 4}


In [ ]:
import math

factorial_dict = {n: math.factorial(n) for n in range(1, 7)}

print(factorial_dict)


{1: 1, 2: 2, 3: 6, 4: 24, 5: 120, 6: 720}


In [ ]:
#Convert two lists into a dictionary using dictionary comprehension.
keys = ['a', 'b', 'c', 'd']
values = [1, 2, 3, 4]

# Using dictionary comprehension to create the dictionary
result_dict = {keys[i]: values[i] for i in range(len(keys))}

print(result_dict)


{'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [ ]:

original_dict = {'a': 1, 'b': 2, 'c': 3}
reversed_dict = {}
for key, value in original_dict.items():
    reversed_dict[value] = key

print(reversed_dict)


{1: 'a', 2: 'b', 3: 'c'}


In [ ]:

#Create a frequency count of characters in a string using dictionary comprehension.

input_string = "hello world"

# Using dictionary comprehension to count character frequencies
char_count = {char: input_string.count(char) for char in set(input_string)}

print(char_count)


In [ ]:
dict1 = {'a': 1, 'b': 2, 'c': 3}
dict2 = {'b': 20, 'c': 30, 'd': 40}


merged_dict = {}

# Get the union of the keys from both dictionaries
all_keys = set(dict1) | set(dict2)


for key in all_keys:

    if key in dict1:
        merged_dict[key] = dict1[key]
    else:
        merged_dict[key] = dict2[key]

print(merged_dict)


{'d': 40, 'c': 3, 'b': 2, 'a': 1}


In [ ]:
#Write a function to calculate the area of a rectangle.


# Area of rectangle = length * width

def calculate_area(length, width):

    return length * width


print(calculate_area(4,6))


24


In [ ]:
#Create a module with a function to check whether a number is even or odd.

def check_even_odd(number):
    if number % 2 == 0:
        return "Even"
    else:
        return "Odd"

nu = int(input("value :"))
print(check_even_odd(nu))

value :78
Even


In [ ]:
#Write a function to return the maximum of three numbers

def maximum_of_three(a, b, c):
    if a >= b and a >= c:
        return a
    elif b >= a and b >= c:
        return b
    else:
        return c

import sys
sys.path.append('/path/to/math_operations_directory')

from math_operations import add, subtract, multiply, divide
print(maximum_of_three(4,6,8))

8


In [ ]:
#Create a package containing modules for basic arithmetic operations (add, subtract, multiply, divide).

import sys
# Assuming math_operations.py is in the same directory as this script
sys.path.append('/tmp')
#def add
#/tmp/matha_operationas

#from tmp.matha_operationas import add
from tmp import matha_operationas

result_add = matha_operationas.add(5, 3)
print(f"Addition: {result_add}")



AttributeError: module 'tmp.matha_operationas' has no attribute 'add'

In [ ]:
import sys

# Add the correct directory to the path
sys.path.append('/tmp')

# Import the module and function
from matha_operationas import add

# Use the add function
result_add = add(5, 3)
print(f"Addition: {result_add}")


Addition: 8


In [ ]:
import sys

print(sys.version)

3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]


# New Section

In [ ]:
#Write a function to compute the Fibonacci sequence up to a given number using recursion.
def fibonacci(n):
    """Return the nth Fibonacci number."""
    if n <= 1:
        return n
    else:
        return fibonacci(n - 1) + fibonacci(n - 2)

fibonacci(9)



34

In [ ]:

import csv_filter
csv.
# Example condition function to filter rows
def condition(row):
    # Example: filter rows where the value in the second column (index 1) is greater than 50
    return int(row[1]) > 50  # Assumes the second column contains numeric values

# Path to the input CSV file
input_file = 'input_data.csv'

# Read the CSV file
header, rows = csv_filter.read_csv(input_file)

# Filter the rows based on the condition
filtered_rows = csv_filter.filter_rows(rows, condition)

# Path to the output CSV file
output_file = 'filtered_data.csv'

# Save the filtered rows to a new CSV file
csv_filter.save_filtered_csv(output_file, header, filtered_rows)

print(f"Filtered data saved to {output_file}")


ModuleNotFoundError: No module named 'csv_filter'

In [ ]:
def nth_root(x, n):
    """
    Calculate the n-th root of a number x.

    Args:
        x: The number to take the n-th root of.
        n: The degree of the root (e.g., 2 for square root, 3 for cube root).

    Returns:
        The n-th root of x.

    Raises:
        ValueError: If n is 0 or x is negative for even n.
        TypeError: If x or n are not numbers.
    """
    try:
        # Ensure the inputs are valid numbers
        if not isinstance(x, (int, float)) or not isinstance(n, (int, float)):
            raise TypeError("Both x and n must be numbers (int or float).")

        # Handle the case where the root degree is 0
        if n == 0:
            raise ValueError("The root degree n cannot be zero.")

        # Handle the case for even roots of negative numbers
        if x < 0 and n % 2 == 0:
            raise ValueError("Cannot compute an even root of a negative number.")

        # Calculate the n-th root
        return x ** (1 / n)

    except ValueError as ve:
        return f"Error: {ve}"
    except TypeError as te:
        return f"Error: {te}"

# Example usage:
print(nth_root(16, 2))
print(nth_root(27, 3))
print(nth_root(-27, 3)) # Should print -3.0 (Cube root of -27)
print(nth_root(-16, 2)) # Should print an error message
print(nth_root(16, 0))  # Should print an error message
print(nth_root('16', 2)) # Should print an error message


4.0
3.0
(1.5000000000000004+2.598076211353316j)
Error: Cannot compute an even root of a negative number.
Error: The root degree n cannot be zero.
Error: Both x and n must be numbers (int or float).


In [ ]:
#Extract the first three elements from a list.


my_list = [10, 20, 30, 40, 50]


first_three_elements = my_list[:3]

print(first_three_elements)



[10, 20, 30]


In [ ]:
#Reverse a list using slicing.
l = [1,2,3,4,5]
l[::-1]


[5, 4, 3, 2, 1]

In [ ]:
# Sample string
my_string = "abcdefg"

# Extract every second character using slicing
every_second_char = my_string[::2]

print(every_second_char)


aceg


In [ ]:
#Extract the middle 3 elements from a list with an odd number of elements.
# Sample list with an odd number of elements
my_list = [10, 20, 30, 40, 50, 60, 70]


middle_index = len(my_list) // 2

# Extract the middle 3 elements
middle_three_elements = my_list[middle_index - 1 : middle_index + 2]

print(middle_three_elements)


[30, 40, 50]


In [ ]:
#Split a list into two halves using slicing

# Sample list
my_list = [10, 20, 30, 40, 50, 60]

# Calculate the middle index
middle_index = len(my_list) // 2

# Split the list into two halves
first_half = my_list[:middle_index]
second_half = my_list[middle_index:]

print("First Half:", first_half)
print("Second Half:", second_half)


First Half: [10, 20, 30]
Second Half: [40, 50, 60]


In [ ]:
#Slice a NumPy array to extract a sub-matrix.
import numpy as np

# Create a 4x4 NumPy array
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

# Extract a sub-matrix (e.g., rows 1 to 2 and columns 2 to 3)
sub_matrix = matrix[1:3, 2:4]

print("Original Matrix:")
print(matrix)

print("\nExtracted Sub-Matrix:")
print(sub_matrix)



Original Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Extracted Sub-Matrix:
[[ 7  8]
 [11 12]]


In [ ]:
# Define the list
lst = [1, 2, 3, 4, 5]

# Specify the number of positions to rotate
n = 3  # Rotate by 3 positions

# Rotate the list
rotated_list = lst[-n:] + lst[:-n]

print("Original List:", lst)
print("Rotated List:", rotated_list)


Original List: [1, 2, 3, 4, 5]
Rotated List: [3, 4, 5, 1, 2]
